### ISSUE TITLE
MS Windows support

### ISSUE THREAD

**Issue by jayvdb** [drmikehenry/findx#6]
How do you feel about providing MS Windows support?
A simple approach would be to bundle a GNU `find` and `xargs` (from http://gnuwin32.sourceforge.net/packages/findutils.htm ?) into a win32 wheel.  If you'd be ok accepting this, I could send a PR to this effect fairly quickly.

A crazier approach would be to attempt to use MS `find` where possible (should be ok for simple find only commands), and/or emulate the rest, possibly using external packages like https://pypi.python.org/pypi/findtools (see https://github.com/ewiger/findtools/issues/2) and https://pypi.python.org/pypi/ypipe .

**Comment by drmikehenry** [comment]
While I like the idea of using ``findx`` on Windows, it seems like it should be up to the user to supply executables for ``find`` and ``xargs``, since ``findx`` is just a convenience wrapper for these programs.  Maybe having a separate Python package that exposes GNU ``find`` and ``xargs`` would work for you.  If you were to create a new Python package (say, ``gnufindxargs``) that exposes the two executables on the ``PATH`` under the names ``gnufind.exe`` and ``gnuxargs.exe``, then I could extend ``findx`` to probe first for ``gnufind`` and then for ``find`` (and similarly for ``gnuxargs``/``xargs``).  This would be helpful for non-Windows users as well (e.g., on OS X or other non-GNU Unix-like platforms), as they'd be able to install ``gnufind`` and ``gnuxargs`` in the ``PATH`` without colliding with their own native ``find``/``xargs`` utilities.

**Comment by drmikehenry** [comment]
Version 0.9.11 of `findx` now support configuration of a number of settings, including settings for choosing the executable location for `find`, `xargs`, and `grep`.  These default to looking for `gnufind`, `gnuxargs`, and `gnugrep` first, falling back to `find`, `xargs`, and `grep`, respectively.  Windows users with the `gnu`-prefixed executables in their paths will not need to configure anything extra to use `findx`.  Users with these utilities installed but not on the `PATH` (perhaps as part of installing Git-Bash) can create a configuration file to point at the utilities using absolute paths.  I think this should give enough flexibility to make `findx` useful on Windows.

**Comment by jayvdb** [comment]
Thank you.  That solves many issues with using findx on MS Windows.
